TARGET=x86_64-elf
PREFIX=$HOME/$TARGET
export PATH=$PREFIX/bin:$PATH

SRC_PREFIX=$HOME/src

BINUTILS_SRC_DIR=$SRC_PREFIX/binutils
BINUTILS_BUILD_DIR=$SRC_PREFIX/build-binutils
BINUTILS_CONFIGURE=$BINUTILS_SRC_DIR/binutils-2.25.1/configure

GCC_SRC_DIR=$SRC_PREFIX/gcc
GCC_BUILD_DIR=$SRC_PREFIX/build-gcc
GCC_CONFIGURE=$GCC_SRC_DIR/gcc-4.9.3/configure

NEWLIB_SRC_DIR=$SRC_PREFIX/newlib-cygwin
NEWLIB_BUILD_DIR=$SRC_PREFIX/build-newlib
NEWLIB_CONFIGURE=$NEWLIB_SRC_DIR/newlib-cygwin/configure

EFI_SRC_DIR=$SRC_PREFIX/gnu-efi
